//
//  Workspace.swift
//  Packages
//
//  Created by 조용인 on 5/9/25.
//

import ProjectDescription

let workspace = Workspace(
  name: "Sseudam",
  projects: [
    "./Projects/**" /// `Workspace`에 포함할 프로젝트 경로 (현재는 `Projects` 폴더 내 모든 프로젝트)
  ],
  schemes: [
    .scheme(
      /// `develop` 환경에서 사용할 Scheme 이름
      name: "develop",
      buildAction: .buildAction(
        targets: [.project(path: "./Projects/Sseudam", target: "Sseudam_Develop")] /// `develop` 환경에서 사용할 `.app` Target 이름
      ),
      runAction: .runAction(configuration: .debug), /// 옵션으로 제공되는 `.debug` 전용 Configuration (실제 이름은 `Debug.xcconfig`)
      archiveAction: .archiveAction(configuration: .debug),
      profileAction: .profileAction(configuration: .debug),
      analyzeAction: .analyzeAction(configuration: .debug)
    ),
    .scheme(
      name: "release", /// `release` 환경에서 사용할 Scheme 이름",
      buildAction: .buildAction(
        targets: [.project(path: "./Projects/Sseudam", target: "Sseudam")] /// `release` 환경에서 사용할 `.app` Target 이름
      ),
      runAction: .runAction(configuration: .release), /// 옵션으로 제공되는 `.release` 전용 Configuration (실제 이름은 `Release.xcconfig`)
      archiveAction: .archiveAction(configuration: .release),
      profileAction: .profileAction(configuration: .release),
      analyzeAction: .analyzeAction(configuration: .release)
    )
  ],
  /// `Workspace`에 포함된 모든 프로젝트에 대해 자동으로 Scheme을 생성하는 옵션 (기본값: `.enabled`)
  /// `disabled`로 설정하면 내가 직접 Scheme을 생성해야 함
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
